version: '3'
services:

#    #PHP Service
    app:
        image: registry.ant-tech.asia/infras/php-fpm:latest
        container_name: point_app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./dev/php/custom.conf:/usr/local/etc/php-fpm.d/custom.conf
            - ./dev/logs:/usr/local/var/log
        networks:
            - point-app-network
#
#    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: point_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8084:80"
        volumes:
            - ./:/var/www
            - ./dev/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - point-app-network

    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: point_db
        restart: unless-stopped
        tty: true
        ports:
            - "33010:3306"
        environment:
            MYSQL_DATABASE: point-db
            MYSQL_ROOT_PASSWORD: ant.tech.asia
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./dev/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - point-app-network

#Docker Networks
networks:
    point-app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
